server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    template:
      default-topic: health.raw.google

google-fit-integration:
  base-url: ${GOOGLE_FIT_INTEGRATION_BASE_URL}
  timeout: 5000

auth-service:
  base-url: ${AUTH_SERVICE_BASE_URL}

jwt:
  secret:
    access: ${JWT_SECRET_ACCESS}
