apiVersion: v1
kind: Secret
metadata:
  name: device-sync-service-secrets
  namespace: lissa-fit
type: Opaque
stringData:
  JWT_SECRET_ACCESS: "Y5ncOVqSI/HnJisBxE0TDsk/3cMP/FbwMDL+elybXkqsmpjNIqbjwCCOM8wTznVkqxeYZqf+ppsr4wzHNt8peA=="
  ENCRYPT_SECRET: "i1Gzkvgov/+JojXyEEIoB8+/204Ow/22EWSQfuAaEwo="